import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, extname, resolve } from 'node:path';
import { PDFDocument } from '@cantoo/pdf-lib';
import zlib from 'node:zlib';
function solidPng(w,h,[r,g,b]){const raw=Buffer.alloc((w*3+1)*h);for(let y=0;y<h;y++){const row=y*(w*3+1);raw[row]=0;for(let x=0;x<w;x++){raw[row+1+x*3]=r;raw[row+2+x*3]=g;raw[row+3+x*3]=b;}}const idat=zlib.deflateSync(raw);const chunk=(t,d)=>{const buf=Buffer.alloc(12+d.length);buf.writeUInt32BE(d.length,0);buf.write(t,4);d.copy(buf,8);buf.writeUInt32BE(zlib.crc32(buf.subarray(4,8+d.length))>>>0,8+d.length);return buf;};const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(w,0);ihdr.writeUInt32BE(h,4);ihdr[8]=8;ihdr[9]=2;return Buffer.concat([Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]),chunk('IHDR',ihdr),chunk('IDAT',idat),chunk('IEND',Buffer.alloc(0))]);}
await mkdir('tmp-dbg2',{recursive:true});
const doc = await PDFDocument.create();
const img = await doc.embedPng(solidPng(400,300,[200,80,80]));
const img2 = await doc.embedPng(solidPng(200,200,[80,80,200]));
const p1 = doc.addPage([595,842]); p1.drawImage(img,{x:80,y:400,width:400,height:300});
const p2 = doc.addPage([595,842]); p2.drawImage(img2,{x:100,y:400,width:200,height:200});
await writeFile('tmp-dbg2/t.pdf', await doc.save());
const OUT = resolve('out');
const MIME = {'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.wasm':'application/wasm','.json':'application/json','.txt':'text/plain','.svg':'image/svg+xml'};
const server = createServer(async (req,res)=>{ try{ let p=decodeURIComponent(new URL(req.url,'http://x').pathname); if(p.endsWith('/'))p+='index.html'; let f=join(OUT,p); if(!existsSync(f)&&!extname(p))f=join(OUT,p,'index.html'); const d=await readFile(f); res.writeHead(200,{'Content-Type':MIME[extname(f)]??'application/octet-stream'}); res.end(d);}catch{res.writeHead(404);res.end();} });
await new Promise(r=>server.listen(4890,r));
const page = await (await chromium.launch()).newPage();
page.on('pageerror', e=>console.log('[pageerror]', String(e).slice(0,400)));
await page.goto('http://localhost:4890/extract-images/', {waitUntil:'networkidle'});
await page.locator('input[type="file"]').first().setInputFiles('tmp-dbg2/t.pdf');
await page.getByText('t.pdf').waitFor({timeout: 10000});
await page.waitForTimeout(300);
await page.getByRole('button', {name: /^Extract images$/}).click();
await page.getByText('Your file is ready').waitFor({ timeout: 60000 });
console.log('PASS: result card shown, zip =', (await page.locator('body').innerText()).includes('images.zip'));
await page.context().browser().close(); server.close();
